### ISSUE TITLE
A possible mistake in the estimation basis of SDR

### ISSUE THREAD

**Issue by I-zhouqh** [SvenSerneels/direpack#13]
Thanks for the package you provide, and I found a confusing problem.
in src/direpack/sudire/sudire.py Line 489. When using scale, x_loadings should be set to N2 multiply P, not P, because we do scale. 
I notice you intended to do so in Line225 in src/direpack/sudire/_sudire_utils.py (take SIR for example), but x passed to this function has already been scaled, so variable "signsqrt" in this function is always identity matrix, which can not function as we want.

**Comment by SvenSerneels** [comment]
Thanks for pointing this out. Issue will be fixed in release 1.0.18.
