### ISSUE TITLE
`p` should never be smaller than `n_components` in `sprm.fit`

### ISSUE THREAD

**Issue by MattWenham** [SvenSerneels/direpack#3]
The variable `p` should never be smaller than `n_components` in `sprm.fit` otherwise an error occurs. This is checked for at the top of `fit` but `p` can be redefined at line 185.

Inserting as line 186:
```
            self.n_components = min(p, self.n_components)
```
...appears to fix the issue, but I have not done extensive testing. It may also be advisable to raise a warning if `n_components` is reduced in this way.

**Comment by MattWenham** [comment]
My apologies, you are right. However, on line 185, `p` can be redefined to be less than `n_components` which then causes issues further down the line.

**Comment by SvenSerneels** [comment]
Have you recently run `pip intsall --upgrade direpack`? The code quote you are citing does not occur in the actual version of `sprm.py`.

**Comment by MattWenham** [comment]
Line 185 of sprm.py reads:

`p = len(vars_to_keep)`

If `p` is redefined at this point to be smaller than `n_components`, the code fails downstream.

**Comment by SvenSerneels** [comment]
Correct, fixed in version 1.0.6. Thanks for the input.
