### ISSUE TITLE
gsspp.GenSpatialSignPrePprocessor().transform() is not working

### ISSUE THREAD

**Issue by shinhongwu** [SvenSerneels/direpack#8]
Dear sirs,

I like to make spatial sign transform for my data when I come across your module and found it won't work.
My codes is as the following:

`scaler = gsspp.GenSpatialSignPrePprocessor(center = 'kstepLTS', fun = 'ball').fit(X_train)`
`X_scaled = scaler.transform(X_train)`

It won't work for scaler don't have the `transform` method due to no object type is defined which makes it no attribute or method bestowed upon.  The error message is as the following:

AttributeError: 'NoneType' object has no attribute 'transform'

maurice

**Comment by SvenSerneels** [comment]
In your code `scaler` corresponds to the `fit` sttribute in the object, which does not have a `transform` attribute by itself. 
Instead, define `scaler` at the level of the GSSPP object: 

    scaler = gsspp.GenSpatialSignPrePprocessor(center = 'kstepLTS', fun = 'ball')
    scaler.fit(X_train)
    X_scaled = scaler.transform(X_train)

**Comment by SvenSerneels** [comment]
Will close the issue as there are no further questions since the comment above.
